name: Link PR to Issue in Development

on:
  pull_request:
    types: [opened, edited, reopened]

jobs:
  link-to-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Extract Issue Number from PR Title
        id: extract-issue
        run: |
          ISSUE_NUMBER=$(echo "${{ github.event.pull_request.title }}" | grep -oP '(?<=#)\d+')
          echo "::set-output name=ISSUE_NUMBER::$ISSUE_NUMBER"

      - name: Output Issue Number
        run: echo "Extracted Issue Number is ${{ steps.extract-issue.outputs.ISSUE_NUMBER }}"

      - name: Use the Issue Number in Another Step (Example)
        if: steps.extract-issue.outputs.ISSUE_NUMBER != ''
        run: echo "The PR is related to Issue #${{ steps.extract-issue.outputs.ISSUE_NUMER }}"
