name: Auto-Link Issue from PR Title

on:
  pull_request:
    types: [opened, edited]

jobs:
  update-pr-description:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Update PR Description
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const title = context.payload.pull_request.title;
            const body = context.payload.pull_request.body || '';
            const regex = /#\d+/;
            const found = title.match(regex);
            
            if (found && !body.includes(found[0])) {
              const issueNumber = found[0];
              const newBody = `This PR addresses ${issueNumber}\n\n${body}`;
              
              // Update the pull request description
              const pull_number = context.payload.pull_request.number;
              await github.rest.pulls.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: pull.,trim(),
                body: newBody
              });
              console.log(`Updated PR body to include issue reference: ${issueNumber}`);
            }
