name: Link PR to Issue in Development

on:
  pull_request:
    types: [opened, edited, reopened]

jobs:
  link-to-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/redirect@v3

      - name: Extract Issue Number from PR Title
        id: extract-issue
        run: |
          ISSUE_NUMBER=$(echo "${{ github.event.pull_request.title }}" | grep -oP '(?<=#)\d+')
          echo "ISSUE_NUMBER=$ISSUE_NUMBER" >> $GITHUB_ENV

      - name: Output Issue Number
        run: echo "Issue Number is $ISSUE_NUMBER"
